### ISSUE TITLE
連絡用 for fujitakyosuke

### ISSUE THREAD

**Issue by doish** [doish/contact#1]
連絡用のissueです。自由に書き込んでみてください。

**Comment by doish** [comment]
@fujitakyosuke
メンションのテスト

**Comment by fujitakyosuke** [comment]
土井さん
お疲れ様です。通知に気が付かず連絡が遅くなってしまい大変申し訳ございません……。
引き続きどうぞ宜しくお願いいたします。

**Comment by doish** [comment]
別で連絡可能なのでクローズします
