### ISSUE TITLE
連絡用 for rtk2

### ISSUE THREAD

**Issue by doish** [doish/contact#2]
連絡用のissueです。自由に書き込んでみてください。

**Comment by doish** [comment]
@rtk2
メンションのテスト

**Comment by rtk2** [comment]
テスト送信です。

**Comment by doish** [comment]
前回口頭で説明できていなくて申し訳ないのですが、
英語でinviteのメール"doish invited you to doish/contact"が飛んでいるので、承諾してもらえますか？
そうするとissueへのアサイン（割当）がこちらでできるようになります。
よろしくお願いします。

**Comment by doish** [comment]
@rtk2 さん
https://github.com/doish/contact/issues/5
に、Macの場合の導入手順を少し詳しく書きました。
引っかかりポイントが満載で申し訳ないです。あまり無理はせず、対面の機会を作っていただくなど検討ください。

**Comment by rtk2** [comment]
＠doish さん
お疲れ様です。
全然ご連絡せずにすみません。Macでの手順説明ありがとうございます。現状としてComposer はインストールできたかな？という所です。ただやはり自分一人では難しく、直接御指導いただきたく思います。

**Comment by doish** [comment]
別で連絡可能なのでクローズします
